# Generated by Django 6.0.1 on 2026-02-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=50)),
                ('ocupado', models.BooleanField()),
                ('condicao', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Defeituoso', 'Defeituoso')], default='Novo', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
